# Generated by Django 5.1.4 on 2025-01-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
